<a href="https://colab.research.google.com/github/ggonz105/MAT-421/blob/main/Module_D_Sections_1_1_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Section 1.1 Introduction**

Linear Algebra is a mathematic field that is widely used and plays an important role in data sciene and machine learning.

Some basic linear algebra concepts include vector spaces, orthogonality, eigenvalues, and matrix decompostition.

**Section 1.2 Elements of Linear Algebra**

Linear Combination
* A new vector constructed from a subset by multiplying each vector by a constant and adding the results

In [7]:
# Linear Combination Example
import numpy as np

x = np.array([[5, 7, 2]])
y = np.array([[8, 4, -2]])
z = np.array([[3, 9, -4]])

a = 2*x + 3*y + 4*z;
print(A)

[[ 9 -5  2]
 [ 2  7 -4]
 [ 5  8 -1]]


Linear Subspace
* A subset that is closed under vector addition and scalar multiplication
* Satisfies: for all u1, u2 ∈ U and α ∈ R, u1 + u2 ∈ U, and
α u1 ∈ U

Span
* The set of all linear combinations
* Every span is a linear subspace

Column Space
* The span of the columns of a given matrix A

Linear Independence
* A list of vectors is linearly independent if none of them can be written as a linear combination of the others
* Vectors are linearly independent if the determinant does not equal 0

In [8]:
# Example of Independent and Dependent Vectors

A = np.array([[9, -5, 2], [2, 7, -4], [5, 8, -1]])
print(np.linalg.det(A)) # Non zero determinant, therefore linearly independent

B = np.array([[0, 0, 0], [2, 7, -4], [5, 8, -1]])
print(np.linalg.det(B)) # Determinant = 0, therefore linearly dependent

277.0
0.0


Dimension Theorem
* If U is a linear subspace of V, any basis of U will have the same number of elements. Additionally, all bases of U will have the same length and the same number of elements. The number of elements is denoted as the dimension

**Orthogonality**
* A set of vectors are orthonormal if they sum to the zero vector and one of them had a magnitude of 1
* The eigenvalue of a square matrix exists if there exists a nonzero vector such that Ax = λx

In [9]:
# A demonstration of finding eigenvalues and eigenvectors in Python

import numpy as np
from numpy.linalg import eig

a = np.array([[4, 2], [5, 1]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [ 6. -1.]
E-vector [[ 0.70710678 -0.37139068]
 [ 0.70710678  0.92847669]]


**Section 1.3 Linear Regression**

* Linear Regression approximates the relationship between 2 variables with a simple linear equation
* QR decomposition is a useful procedure to solve the least squares problem
* For a given matrix, A, its QR decompisition is such that A=QR where Q is a matrix with the same dimensions as A and R is a suqare matrix with its dimensions determined by the number of columns in A
* Suppose A is a matrix and b is a vector with as many rows as A, Ax = b is best solved using the least-squares problems